services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel-app
    restart: unless-stopped
    ports:
      - "8000:8000"
    volumes:
      - ./:/var/www/html
    user: "${UID:-1000}:${GID:-1000}"
    working_dir: /var/www/html
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_DATABASE=ecommerce
      - DB_USERNAME=laraveluser
      - DB_PASSWORD=laravelpass
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      - db
      - redis

  db:
    image: postgres:15
    container_name: ecommerce-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: laraveluser
      POSTGRES_PASSWORD: laravelpass
      POSTGRES_DB: ecommerce
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  redis:
    image: redis:7
    container_name: ecommerce-redis
    restart: unless-stopped
    ports:
      - "6379:6379"

volumes:
  pgdata: